# Generated by Django 3.2.6 on 2021-09-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
