# Generated by Django 3.2.6 on 2021-09-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('C', 'Client'), ('E', 'Executor'), ('P', 'Planner'), ('M', 'Management')], max_length=1, null=True),
        ),
    ]
