# Generated by Django 3.2.7 on 2021-09-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('1', 'Client'), ('2', 'Executor'), ('3', 'Planner'), ('4', 'Management')], max_length=1, null=True),
        ),
    ]
