# Generated by Django 3.2.7 on 2021-09-17 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('1', 'New'), ('2', 'Processing'), ('3', 'Processing (await for approval of the board)'), ('4', 'Await for the payment date'), ('5', 'Rejected'), ('6', 'Finished')], default='1', max_length=1)),
                ('priority', models.CharField(choices=[('1', 'Low'), ('2', 'Middle'), ('3', 'High')], default='1', max_length=1)),
                ('stage', models.CharField(blank=True, choices=[('1', 'In planning'), ('2', 'Is logistic'), ('3', 'In transport'), ('4', 'Process is done'), ('5', 'In complaint')], max_length=1, null=True)),
                ('origin', models.CharField(choices=[('1', 'City'), ('2', 'Country'), ('3', 'Abroad')], max_length=1)),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('1', 'Created'), ('2', 'Started'), ('3', 'Requested for set payment date'), ('4', 'Payment date was set'), ('5', 'Requested for approval of the board'), ('6', 'Accepted by the board'), ('7', 'Finished'), ('8', 'Rejected')], max_length=1)),
                ('recorded_time', models.DateTimeField(auto_now_add=True)),
                ('additional_info', models.CharField(blank=True, max_length=256, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
