# Generated by Django 3.2.6 on 2021-09-18 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_orderlog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executing_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
