# Generated by Django 3.2.6 on 2021-09-19 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210919_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
