# Generated by Django 3.2.6 on 2021-09-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_order_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='event',
            field=models.CharField(choices=[('C', 'Created'), ('S', 'Started'), ('RP', 'Requested for set payment date'), ('P', 'Payment date was set'), ('RA', 'Requested for approval of the board'), ('A', 'Accepted by the board'), ('F', 'Finished'), ('R', 'Rejected'), ('SP', 'Planning end date was set'), ('SL', 'Logistic end date was set'), ('ST', 'Transport end date was set'), ('SD', 'Process end date was set'), ('SC', 'Complaint end date was set')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='origin',
            field=models.CharField(choices=[('CI', 'City'), ('CO', 'Country'), ('A', 'Abroad')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Middle'), ('H', 'High')], default='L', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='stage',
            field=models.CharField(blank=True, choices=[('P', 'In planning'), ('L', 'Is logistic'), ('T', 'In transport'), ('D', 'Process is done'), ('C', 'In complaint')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('P', 'Processing'), ('AA', 'Processing (await for approval of the board)'), ('PA', 'Await for the payment date'), ('R', 'Rejected'), ('F', 'Finished')], default='N', max_length=2),
        ),
    ]
